from lexer import Lexer
from parser_ast import Parser

def main():
    source_code = "result = 5 + 3 * 12 - 2;"
    print(f"Input Code String: \\"{source_code}\\"\\n")

    # Step 1: Initialize Lexer and extract token groupings
    lexer = Lexer(source_code)
    tokens = lexer.tokenize()
    print("--- Tokens Generated by Lexer ---")
    for token in tokens:
        print(token)
        
    # Step 2: Initialize Parser and construct the AST node structure
    parser = Parser(tokens)
    ast_root = parser.parse()
    
    print("\\n--- Abstract Syntax Tree Hierarchy Output ---")
    ast_root.print_tree()

if __name__ == "__main__":
    main()
